"""empty message

Revision ID: 678173723536
Revises: f76ba5795197
Create Date: 2023-01-15 20:01:38.835931

"""
from alembic import op
import sqlalchemy as sa
from app.models.db import environment, SCHEMA
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '678173723536'
down_revision = 'f76ba5795197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_users',
    sa.Column('server_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'user_id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE server_users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###
